name: Deploy the App
on:
  - workflow_dispatch
  - push
jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./app
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
    steps:
      - name: Setup Docker layer caching
        uses: actions/cache@v4
        with:
          path: /var/lib/docker
          key: docker-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            docker-${{ runner.os }}-

      - name: Download the code
        uses: actions/checkout@v6

      - name: Download and install dependencies
        uses: ./.github/actions/cache-deps
        with:
          node-version: '20'

      - name: Run tests
        id: run-tests
        run: npm test

      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v6
        with:
          name: test-report
          path: ./app/test.json

  build:
    needs: test
    outputs:
      app-name: ${{ steps.app-name.outputs.app-name }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Download the code
        uses: actions/checkout@v6

      - name: Download and install dependencies
        uses: ./.github/actions/cache-deps
        with:
          node-version: '20'
          caching: 'false'

      - name: Build the app
        run: npm run build

      - name: Output the app entry name
        id: app-name
        run: |
          find dist/_app/immutable/entry/app*.js -type f -execdir echo 'app-name={}' >> $GITHUB_OUTPUT ';'

      - name: Upload the artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: ./app/dist

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v6
        with:
          name: dist

      - name: Show artifact output
        run: ls

      - name: Show the app name
        run: echo ${{ needs.build.outputs.app-name }}

      - name: Deploy
        run: echo "Deploying the application..."

  report:
    if: failure()
    needs: [test, build, deploy]
    runs-on: ubuntu-24.04
    steps:
      - name: Output information
        run: |
          echo "Runs only if the job is failing "
          echo "${{ toJson(github) }}"
