name: "label issues"

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  assign-label:
    runs-on: ubuntu-24.04
    steps:
      - name: "Assign 'bug' label if issue title contains 'bug'"
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
          --url "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"labels":["bug"]}' \
          --fail
