name: Matrix Demo

on:
  - workflow_dispatch
  - push

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [18, 20, 22]
        os: [ubuntu-24.04, windows-2022, macos-14]
        include:
            - node-version: 20
              os: ubuntu-22.04
        exclude:
          - node-version: 18
            os: macos-14
        
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Download the code
        uses: actions/checkout@v6

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instal Dependencies
        run: npm ci

      - name: Build
        run: npm run build
