name: "Demo Script Injection Workflow"
on:
  issues:
    types: opened

jobs:
  assign-label:
    runs-on: ubuntu-24.04
    steps:
      - name: "Assign label"
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$issue_title" == *"bug"* ]]; then
              echo "Issue is about a bug"
          else
              echo "Issue is not about a bug"
          fi
